import { ENUM_INTERCEPTOR_TOKENS } from "../enums";

export const INTERCEPTOR_TOKENS_TYPES = {
	// Prisma Client
	PRISMA_CLIENT_DB: Symbol.for(ENUM_INTERCEPTOR_TOKENS.PRISMA_CLIENT_DB),

	// Health Check
    HEALTHCHECK_USECASE: Symbol.for(ENUM_INTERCEPTOR_TOKENS.HEALTHCHECK_USECASE),
    HEALTHCHECK_CONTROLLER: Symbol.for(ENUM_INTERCEPTOR_TOKENS.HEALTHCHECK_CONTROLLER),

	// Currency
	CURRENCY_USECASE: Symbol.for(ENUM_INTERCEPTOR_TOKENS.CURRRENCY_USECASE),
	CURRENCY_REPO: Symbol.for(ENUM_INTERCEPTOR_TOKENS.CURRENCY_REPO),
	CURRENCY_CONTROLLER: Symbol.for(ENUM_INTERCEPTOR_TOKENS.CURRENCY_CONTROLLER),

	// COUNTRY
	COUNTRY_USECASE: Symbol.for(ENUM_INTERCEPTOR_TOKENS.COUNTRY_USECASE),
	COUNTRY_REPO: Symbol.for(ENUM_INTERCEPTOR_TOKENS.COUNTRY_REPO),
	COUNTRY_CONTROLLER: Symbol.for(ENUM_INTERCEPTOR_TOKENS.COUNTRY_CONTROLLER),
};
