/**
 * src/core/enums/interceptors.enum.ts
 *
 * Interceptors Enums
 * Included all interceptors thru this application
 *
 * @author JKDEVELOPER
 * @nickname JK
 * @email jktan0504@hotmail.com
 *
 * @last_update: 30 April 2024
 */

export enum ENUM_INTERCEPTOR_TOKENS {
	// Prisma Client
	PRISMA_CLIENT_DB = 'PRISMA_CLIENT_DB',

    // Health Check
	HEALTHCHECK_USECASE = 'HEALTHCHECK_USECASE',
    HEALTHCHECK_CONTROLLER = 'HEALTHCHECK_CONTROLLER',

	// MEDIA
	MEDIA_USECASE = 'MEDIA_USECASE',
	MEDIA_REPO = 'MEDIA_REPO',
	MEDIA_CONTROLLER = 'MEDIA_CONTROLLER',
	MEDIA_FILE_USECASE = 'MEDIA_FILE_USECASE',
	MEDIA_FILE_REPO = 'MEDIA_FILE_REPO',
	MEDIA_FILE_CONTROLLER = 'MEDIA_FILE_CONTROLLER',
	FILE_UPLOAD_USECASE = 'FILE_UPLOAD_USECASE',
	FILE_UPLOAD_CONTROLLER = 'FILE_UPLOAD_CONTROLLER',

	// Country
	CURRRENCY_USECASE = 'CURRRENCY_USECASE',
	CURRENCY_REPO = 'CURRENCY_REPO',
	CURRENCY_CONTROLLER = 'CURRENCY_CONTROLLER',
	COUNTRY_USECASE = 'COUNTRY_USECASE',
	COUNTRY_REPO = 'COUNTRY_REPO',
	COUNTRY_CONTROLLER = 'COUNTRY_CONTROLLER',

	// COMPANY
	COMPANY_CATEGORY_USECASE = 'COMPANY_CATEGORY_USECASE',
	COMPANY_CATEGORY_REPO = 'COMPANY_CATEGORY_REPO',
	COMPANY_CATEGORY_CONTROLLER = 'COMPANY_CATEGORY_CONTROLLER',
	COMPANY_USECASE = 'COMPANY_USECASE',
	COMPANY_REPO = 'COMPANY_REPO',
	COMPANY_CONTROLLER = 'COMPANY_CONTROLLER',

	// ROLE
	ROLE_USECASE = 'ROLE_USECASE',
	ROLE_REPO = 'ROLE_REPO',
	ROLE_CONTROLLER = 'ROLE_CONTROLLER',
	PERMISSION_USECASE = 'PERMISSION_USECASE',
	PERMISSION_REPO = 'PERMISSION_REPO',
	PERMISSION_CONTROLLER = 'PERMISSION_CONTROLLER',
	RBAC_USECASE = 'RBAC_USECASE',
	RBAC_REPO = 'RBAC_REPO',
	RBAC_CONTROLLER = 'RBAC_CONTROLLER',

	// AUTHENTICATE
	AUTH_USECASE = 'AUTH_USECASE',
	AUTH_CONTROLLER = 'AUTH_CONTROLLER',
	AUTH_SSO_PROVIDER_USECASE = 'AUTH_SSO_PROVIDER_USECASE',
	AUTH_SSO_PROVIDER_REPO = 'AUTH_SSO_PROVIDER_REPO',
	AUTH_SSO_PROVIDER_CONTROLLER = 'AUTH_SSO_PROVIDER_CONTROLLER',
	AUTH_USER_LOGIN_TOKEN_USECASE = 'AUTH_USER_LOGIN_TOKEN_USECASE',
	AUTH_USER_LOGIN_TOKEN_REPO = 'AUTH_USER_LOGIN_TOKEN_REPO',
	AUTH_USER_LOGIN_TOKEN_CONTROLLER = 'AUTH_USER_LOGIN_TOKEN_CONTROLLER',
	AUTH_FORGET_PASSWORD_USECASE = 'AUTH_FORGET_PASSWORD_USECASE',
	AUTH_FORGET_PASSWORD_REPO = 'AUTH_FORGET_PASSWORD_REPO',
	AUTH_FORGET_PASSWORD_CONTROLLER = 'AUTH_FORGET_PASSWORD_CONTROLLER',
	AUTH_VERIFY_OTP_USECASE = 'AUTH_VERIFY_OTP_USECASE',
	AUTH_VERIFY_OTP_REPO = 'AUTH_VERIFY_OTP_REPO',
	AUTH_VERIFY_OTP_CONTROLLER = 'AUTH_VERIFY_OTP_CONTROLLER',	

	// USER
	USER_REFERRAL_CODE_USECASE = 'USER_REFERRAL_CODE_USECASE',
	USER_REFERRAL_CODE_REPO = 'USER_REFERRAL_CODE_REPO',
	USER_REFERRAL_CODE_CONTROLLER = 'USER_REFERRAL_CODE_CONTROLLER',
	USER_SETTING_USECASE = 'USER_SETTING_USECASE',
	USER_SETTING_REPO = 'USER_SETTING_REPO',
	USER_SETTING_CONTROLLER = 'USER_SETTING_CONTROLLER',
	USER_DETAIL_USECASE = 'USER_DETAIL_USECASE',
	USER_DETAIL_REPO = 'USER_DETAIL_REPO',
	USER_DETAIL_CONTROLLER = 'USER_DETAIL_CONTROLLER',
	USER_USECASE = 'USER_USECASE',
	USER_REPO = 'USER_REPO',
	USER_CONTROLLER = 'USER_CONTROLLER',

	// NOTIFICATION
	NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE',
}
